services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpassword
      - POSTGRES_DB=chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=chatuser
      - DB_PASSWORD=chatpassword
      - DB_NAME=chatdb
      - DB_PORT=5432
      - SSL_MODE=disable
      - TIMEZONE=UTC
    depends_on:
      - db
    networks:
      - chat-app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - chat-app-network

networks:
  chat-app-network:
    driver: bridge

volumes:
  postgres_data: